#!/usr/bin/env bash

. /opt/custom/munin/template/plugin.sh

if [ "$1" = 'autoconf' ]; then
    echo yes
    exit 0
fi

if [ "$1" = "config" ]; then

    echo 'graph_title ZFS - ARC Stats'
    echo 'graph_category disk' 
    echo 'graph_scale yes'
    echo 'graph_width 600'

    echo "arc_hits.label ARC Hits"
    echo "arc_hits.draw AREA"
    echo "arc_miss.label ARC Misses"
    echo "arc_miss.draw LINE2"
    exit 0
fi

echo "arc_hits.value $(kstat -p ::arcstats:hits| cut -s -f 2)"
echo "arc_miss.value $(kstat -p ::arcstats:misses| cut -s -f 2)"
