#!/bin/bash

if [ "$1" = "autoconf" ]; then
                echo yes
                exit 0
fi

zlines=`/sbin/zpool iostat -v| wc -l|sed 's/ //g'`
ztail=`echo "-"$zlines`
ztmp=/tmp/zpool-io.tmp
zdata=`/sbin/zpool iostat -v 1 1| tail $ztail > $ztmp`
zlist=`cat $ztmp|awk '/alloc/ {next}; /avail/ {next}; /raid/ {next}; /mirror/ {next}; { if ( $4 >=0 ) print $1}'`
zname=`cat $ztmp|awk '/alloc/ {next}; /avail/ {next}; /raid/ {next}; /mirror/ {next}; { if ( $4 >=0 ) print $1}'|awk '{gsub("[^a-zA-Z0-9_]", "_", $1); print}'`
zorder=`for o in $zname; do echo $o'_read '; echo $o'_write '; done`

if [ "$1" = "config" ]; then
        echo 'graph_title zpool iostat'
        echo 'graph_args --base 1000 -l 0'
        echo 'graph_vlabel write - read KBytes/s'
        echo 'graph_category disk'
        echo 'graph_scale yes'
        echo 'graph_width 600'
        echo 'graph_info This graph shows zpool iostat'
        echo 'graph_order '$zorder
        echo $zlist | tr ' ' '\n' | while read i; do
                case $i in
                *) name=`echo $i | awk '{ gsub("[^a-zA-Z0-9_]", "_", $1); print }'` ;;
                esac
                echo $name'_read.label '$i
                echo $name'_read.type GAUGE'
                echo $name'_read.graph no'
                echo $name'_write.label '$i
                echo $name'_write.type GAUGE'
                echo $name'_write.negative '$name'_read'
        done
        exit 0
fi
echo $zlist | tr ' ' '\n' | while read iz; do
        zlabel=`echo $iz|awk '{print $1}'`
        case $iz in
        *) name=`echo $iz | awk '{ gsub("[^a-zA-Z0-9_]", "_", $1); print $1 }'` ;;
        esac
        echo -n $name'_read.value '
        grep $zlabel $ztmp|awk '/M/ {print $6*1000; exit 0}; /K/ {print $6; exit 0}; /[0-9]$/ {print $6/1000; exit 0}'|sed 's/[^0-9,\.]*//g'
        echo -n $name'_write.value '
        grep $zlabel $ztmp|awk '/M/ {print $7*1000; exit 0}; /K/ {print $7; exit 0}; /[0-9]$/ {print $7/1000; exit 0}'|sed 's/[^0-9,\.]*//g'
done

rm $ztmp; touch $ztmp

